# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"
gem 'sinatra-reloader'
gem 'sequel'
gem 'sqlite3'
gem 'pry-byebug'
gem 'haml'
gem 'faye-websocket'
